language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
matrix:
  allow_failures:
    - python: 3.7-dev
install:
  - pip install --upgrade setuptools
  - pip install .
script:
  - python setup.py nosetests
