language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
matrix:
  allow_failures:
    - python: 3.7-dev
install:
  - pip install --upgrade pip setuptools coverage
  - pip install .
script:
  - python -mcoverage run setup.py test
  - python -mcoverage report
